config/routes.rb
DemarcoArchive::Application.routes.draw do

  get 'collection_items/create'
  get 'collection_items/delete'

  delete '/taggings' => 'taggings#destroy'
  post '/taggings' => 'taggings#create'
  get '/taggings' => 'taggings#show'

  get 'password_resets/new'
  get 'password_resets/edit'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/assets/new' => 'assets#new', as: :new_asset
  get '/assets/:url' => 'assets#show', as: :asset
  get '/assets' => 'assets#index', as: :assets
  patch '/assets/:url' => 'assets#update'
  get '/assets/:url/edit' => 'assets#edit', as: :edit_asset
  post '/assets/' => 'assets#create'
  get '/assets/:url/lightbox' => 'assets#lightbox', as: :asset_lightbox
  delete '/assets/:url' => 'assets#delete', as: :delete_asset

  get '/people' => 'people#index'
  get '/people/new' => 'people#new', as: :new_person
  get '/people/:url' => 'people#show', as: :person
  patch '/people/:url' => 'people#update'
  get '/people/:url/edit' => 'people#edit', as: :edit_person
  post '/people' => 'people#create'
  delete '/people/:url' => 'people#destroy', as: :delete_person

  delete 'asset_people' => 'asset_people#destroy'
  post 'asset_people' => 'asset_people#create'

  get '/collections/new' => 'collections#new', as: :new_collection
  get '/collections/:url' => 'collections#show'
  get '/collections/:url/list' => 'collections#show', as: :collection_list
  get '/collections' => 'collections#index'
  patch '/collections/:url' => 'collections#update'
  get '/collections/:url/edit' => 'collections#edit', as: :edit_collection
  get '/collections/public_collections' => 'collections#public_collections', as: :public_collections
  delete '/collections/:url' => 'collections#destroy'
  resources :collections

  post '/collection_items/' => 'collection_items#create'
  delete '/collection_items/' => 'collection_items#delete'

  get 'tags/new' => 'tags#new', as: :new_tag
  get '/tags/:url' => 'tags#show'
  get '/tags' => 'tags#index'
  patch '/tags/:url' => 'tags#update'
  get '/tags/:url/edit' => 'tags#edit', as: :edit_tag
  post '/tags' => 'tags#create'

  get '/search' => 'search#search', as: :search
  post '/search' => 'search#search'

  get '/static_text/edit' => 'static_text#edit'
  patch '/static_text' => 'static_text#update'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get '/users/:url/history' => 'users#history', as: :history
  get '/users/:url/favourites' => 'users#favorites', as: :favorites
  get '/users/:url/dashboard' => 'users#dashboard', as: :dashboard
  post '/users/:url/toggle_admin' => 'users#toggle_admin'

  resources :favorites, only: [:create, :destroy]

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "home#errors", :code => code
  end

  get '/about' => 'home#about'

  post '/home/send_contact' => 'home#send_contact'

  root 'home#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  ## Pagination
  paginates_per 24

  ## Relationships
  has_many :collection_items, :dependent => :destroy
  has_many :assets, through: :collection_items
  belongs_to :user

  ## Can belong to self
  has_many :children, class_name: "Collection", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Collection"

  belongs_to :front_image, :class_name => 'Asset'

  ## Scopes
  scope :by_asset_count, -> { order('collection_items_count DESC') }
  scope :global,  -> { where(public: true) }
  scope :personal, -> { where(public: false) }
  scope :featured, -> { where(featured: true) }
  scope :archive_collections, -> { where(user_id: 0) }
  scope :user_collections, -> (user) {where(user_id: user.id)}

  ## Validations
  validates :title, :presence => true, :uniqueness => true

  ### Sunspot search

  searchable do
    text :title, :boost => 2
    text :description
    integer :collection_items_count
    boolean :public
    integer :user_id
  end

  ## Instance methods
  has_url :url, :generated_from => :title

  def ancestors
    return @ancestors ||= (parent ? (parent.ancestors + [self]) : [self])
  end
  
  def has_parent?
    
  end

  def has_parent?
    return self.parent_id != nil
  end

  ## Class methods
  def self.archive_collection
    return Collection.where(user_id: nil).first
  end

  def self.admin_collections(admin_user)
    if admin_user && admin_user.admin?
      return self.where(:user_id => ["0", admin_user.id])
    else
      return nil
    end
  end
  # scope :main_collections -> { where(:parent_id == nil) }
end

# == Schema Information
#
# Table name: collections
#
#  id                     :integer          not null, primary key
#  title                  :string(255)
#  user_id                :integer
#  public                 :boolean
#  front_image_id         :integer
#  description            :text
#  created_at             :datetime
#  updated_at             :datetime
#  collection_items_count :integer          default(0)
#  parent_id              :integer
#  featured               :boolean
#
# Indexes
#
#  index_collections_on_parent_id  (parent_id)
#

app/controllers/collections_controller.rb
# == Schema Information
#
# Table name: collections
#
#  id                     :integer          not null, primary key
#  title                  :string(255)
#  user_id                :integer
#  public                 :boolean
#  front_image_id         :integer
#  description            :text
#  created_at             :datetime
#  updated_at             :datetime
#  collection_items_count :integer          default(0)
#  parent_id              :integer
#  featured               :boolean
#
# Indexes
#
#  index_collections_on_parent_id  (parent_id)
#

class CollectionsController < ApplicationController
  # before_action :set_collection, only: [:show, :edit, :update, :destroy]
  # before_action :must_be_user, only: [:new, :edit, :destroy, :create, :update]
  before_action :check_permissions, only: [:new, :edit, :destroy, :create, :update]


  # GET /collections
  # GET /collections.json
  def index
    if logged_in?
      @user = current_user
      @personal_collections = @user.collections
    end
    if logged_in? && current_user.admin?
      @user_collections = Collection.where.not(user_id: 0)
    else
      @user_collections = Collection.global.where.not(user_id: 0)
    end

    @archive_collection = Collection.archive_collection
    @archive_collections = @archive_collection.children.order(title: :asc)


  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    if logged_in?
      @user = current_user
    end
    url_rewrite(Collection, params, flash)
    @archive_collection = Collection.archive_collection
    if logged_in? && (@collection.user_id == current_user.id || current_user.admin?)
      @children = @collection.children.order(title: :asc).page params[:page]
      @assets = @collection.assets.page params[:page]
    else
      @children = @collection.children.global.order(title: :asc).page params[:page]
      @assets = @collection.assets.published.page params[:page]
    end
    
    # @assets = @collection.assets.page params[:page]
    @ancestors = @collection.ancestors
  end

  def public_collections

  end


  # GET /collections/new
  def new
    if params[:sub] == "true"
      @parent = Collection.find(params[:parent_id])
    else
      @parent = nil
    end

    @collection = Collection.new
    @archive_collection = Collection.archive_collection
  end

  # GET /collections/1/edit
  def edit
    url_rewrite(Collection, params, flash)

    if @collection.has_parent?
      @parent = Collection.find(@collection.parent_id)
    else
      @parent = nil
    end

    @archive_collection = Collection.archive_collection

    @children = @collection.children.global.page params[:page]
    @assets = @collection.assets.page params[:page]
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    if @collection.save
      flash[:notice] = "Collection was successfully created."
      redirect_to @collection
    else
      flash[:error] = "Collection could not be saved"
      render action: 'new'
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    id = get_id(params[:url])
    
    @collection = Collection.find(id)

    if @collection.update(collection_params)
      redirect_to @collection
    else
      render action: 'edit'
    end

  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:url])
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:url].split('-').first )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:title, :user_id, :global, :front_image_id, :description, :public, :featured, :parent_id)
    end

    def must_be_user
      unless current_user
        redirect_to root_path, notice: "Admin Needed."
      end
    end

    def check_permissions
      unless current_user
        redirect_to root_path, notice: "User account needed."
      end

      @action = params[:action]

      case @action
        when "new","create"
          @parent = params[:sub] == "true" ? Collection.find(params[:parent_id]) : nil

          @archive_collection = Collection.archive_collection

          unless (current_user && current_user.admin?) || (@parent != nil && current_user == @parent.user) || (@parent == nil && @parent != @archive_collection )
            redirect_to root_path, notice: "Admin needed."
          end

        when "edit", "update", "destroy"
          @collection = Collection.find(params[:url])

          if @collection == Collection.archive_collection
            redirect_to root_path, notice: "Cannot edit root collection."
          end

          unless (current_user && current_user.admin?) || (current_user && current_user == @collection.user)
            redirect_to root_path, notice: "Admin needed."
          end
      end
    end
end

app/helpers/collections_helper.rb
# == Schema Information
#
# Table name: collections
#
#  id                     :integer          not null, primary key
#  title                  :string(255)
#  user_id                :integer
#  public                 :boolean
#  front_image_id         :integer
#  description            :text
#  created_at             :datetime
#  updated_at             :datetime
#  collection_items_count :integer          default(0)
#  parent_id              :integer
#  featured               :boolean
#
# Indexes
#
#  index_collections_on_parent_id  (parent_id)
#

module CollectionsHelper
end

app/views/collections/_form.html.haml
%section.single-asset-view.area.new-asset
  %section#single-asset.container
    .single-img.single-block
      -if @collection.front_image
        .single-img.single-block
          =image_tag(@collection.front_image.file.url(:medium))
    =form_for @collection do |f|
      - if @collection.errors.any?
        #error_explanation
          %h2= "#{pluralize(@collection.errors.count, "error")} prohibited this collection from being saved:"
          %ul
            - @collection.errors.full_messages.each do |msg|
              %li= msg
      .single-details.single-block
        .single-extra
          -if sub
            -if parent.id == @archive_collection.id
              %h2
                #{type} site collection
            -else
              %h2
                #{type} subcollection of
                =parent.title
            %br
          -else
            %h2
              #{type} collection
            %br
          .field

            =f.label :title
            %br
            =f.text_field :title

          .field
            =f.label :description
            %br
            =f.text_area :description
          .field
            =f.label "Front Image ID"
            %br
            =f.text_field :front_image_id

            / Disabling current_user id - This is causing overwriting of site collections - need to think about how to manage this.


            =f.hidden_field :user_id, :value => sub ? @collection.user_id == 0 ? 0 : current_user.id : current_user.id

            =f.hidden_field :parent_id, :value => sub ? parent.id : nil


          .field
            =f.label "Public collection"
            =f.check_box :public
          -if current_user.admin?
            .field
              =f.label "Featured collection"
              =f.check_box :featured
            .actions

          = f.submit class: "btn"

app/views/collections/_show_assets_gallery_view.html.haml
.container
  .gallery-header
    Images
.gallery.container.clearfix
  -assets.each do |asset|
    %article#t.gallery-item.gallery-full-item.flex-wrap.flex-center{:id => asset.id}

      -# Thumbnails
      .flex-stretch.flex-wrap.flex-center
        -if asset.media_type == "image"
          =image_tag(asset.file.url(:medium))
        -elsif asset.video?
          =image_tag(asset.thumbnail_url)

      -# Gallery Popup
      -if asset.media_type == "image"
        =link_to(asset_lightbox_path(asset.url), class: "gallery-overlay gallery-popup") do
          -if asset.title == nil
            [untitled]
          -else
            =simple_format(asset.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", ""), {}, wrapper_tag: "h1")
          %section.container.clearfix
      -elsif asset.video?
        =link_to(asset_lightbox_path(asset.url), class: "gallery-overlay gallery-popup") do
          -if asset.title == nil
            [untitled]
          -else
            =simple_format(asset.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", ""), {}, wrapper_tag: "h1")
          %section.container.clearfix
  .clearfix
  =paginate @assets

app/views/collections/_show_collections_gallery_view.html.haml
.gallery.container.clearfix.collection--gallery

  -@children.each do |collection|
    %article#t.gallery-item.gallery-full-item.collection-item{:id => collection.id}
      .gallery-img
        =collection.front_image ? image_tag(collection.front_image.file.url(:medium)) : ""

      -params[:action] == "user_collections" || params[:action] == "show_user_collection" ? collection_url = user_collection_path(@user.url, collection.url) : collection_url = collection_path(collection.url)
      =link_to(collection_url, class: "collection-overlay") do


        .collection-item-text
          %span.collection-item-label View collection
          =simple_format(collection.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", "")+" →", {}, wrapper_tag: "h1")

app/views/collections/_show_collections_list_view.html.haml
.container.collection--list
  -@children.each do |collection|
    %article.collection__list-item{:id => collection.id}
      -@subchildren = collection.children.global.order(title: :asc)

      -params[:action] == "user_collections" || params[:action] == "show_user_collection" ? collection_url = user_collection_path(@user.url, collection.url) : collection_url = collection_path(collection.url)



      -if @subchildren.count >= 1
        =link_to(collection.title, "#"+collection.id.to_s, class: "collection__list-parent hasChildren")
        .collection__list-children{:id => 'list'+collection.id.to_s}
          %span.collection__list-child
            =link_to collection_url+'/list?view=list' do
              View collection
              %span.collection__arrow.-child
          -@subchildren.each do |child|

            -params[:action] == "user_collections" || params[:action] == "show_user_collection" ? child_url = user_collection_path(@user.url, child.url) : child_url = collection_path(child.url)

            %span.collection__list-child
              =link_to child_url do
                =child.title
                %span.collection__arrow.-child
      -else
        =link_to(collection.title, collection_url, class: "collection__list-parent noChildren")

app/views/collections/edit.html.haml
=render partial: 'form', locals: {sub: @collection.has_parent?, parent: @parent, type: "Edit"}
%br
.container
  .gallery-header.clearfix
    %span.gallery-title=@collection.title
    =link_to 'Delete collection', @collection, method: :delete, data: { confirm: 'Are you sure?' }, class: "sub-nav-act"
    %span.bar-dets
      has
      =@collection.assets.count
      -if @collection.assets.count == 1
        image
      -else
        images
      &
      =@collection.children.count
      -if @collection.children.count == 1
        child collection
      -else
        child collections
    -if @collection.parent
      %span.bar-dets
        Parent collection:
        =link_to @collection.parent.title, collection_path(@collection.parent)
    -else
      %span.bar-dets
        =link_to "Top Level Collections", collections_path

    .gallery.container.clearfix
      -@assets.each do |asset|
        %article#t.gallery-item.gallery-full-item.flex-wrap.flex-center{:id => asset.id}

          -# Thumbnails
          .flex-stretch.flex-wrap.flex-center
            -if asset.media_type == "image"
              =image_tag(asset.file.url(:medium))
            -elsif asset.media_type == "video"
              =image_tag(asset.file.url(:thumb))

          -# Gallery Popup
          -if asset.media_type == "image"
            =link_to(asset_lightbox_path(asset.url), class: "gallery-overlay gallery-popup") do
              -if asset.title == nil
                [untitled]
              -else
                =simple_format(asset.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", ""), {}, wrapper_tag: "h1")
              %section.container.clearfix
          -elsif asset.media_type == "video"
            =link_to(asset.file.url(:medium), class: "gallery-overlay gallery-popup mfp-iframe") do
              -if asset.title == nil
                [untitled]
              -else
                =simple_format(asset.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", ""), {}, wrapper_tag: "h1")
              %section.container.clearfix
      .clearfix
      =paginate @assets

      / .search-area
      /   %h1 Search Area
      /   Put search interface here where clicks on images add to collection
      /   %br

app/views/collections/index.html.haml
%section.gallery-view.area

  -if @personal_collections
    -# Your Collections
    %section.container
      .gallery-header
        %span.gallery-title Your Collections
        %span.bar-dets
          = @personal_collections.count.to_s + " collections"
    .gallery.container.clearfix
      -@personal_collections.each do |collection|
        %article#t.gallery-item.gallery-full-item.collection-item{:id => collection.id}
          .gallery-img
            =image_tag(collection.front_image.file.url(:medium)) if collection.front_image
            =link_to(collection_path(collection), class: "collection-overlay") do
              .collection-item-text
                %span.collection-item-label Collection
                =simple_format(collection.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", "")+" →", {}, wrapper_tag: "h1")



  -# Site Collections
  %section.container
    .gallery-header
      %span.gallery-title Site Collections
      %span.bar-dets
        = @archive_collections.count.to_s + " collections"
  .gallery.container.clearfix
    -# -@archive_collections[0..2].each do |collection|
    -@archive_collections.each do |collection|
      %article#t.gallery-item.gallery-full-item.collection-item{:id => collection.id}
        .gallery-img
          =image_tag(collection.front_image.file.url(:medium)) if collection.front_image
          =link_to(collection_path(collection), class: "collection-overlay") do
            .collection-item-text
              %span.collection-item-label Collection
              =simple_format(collection.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", "")+" →", {}, wrapper_tag: "h1")

    -# %article#t.gallery-item.gallery-full-item.collection-item
    -#   .gallery-img
    -#
    -#     =link_to(collection_path(@archive_collection), class: "collection-overlay") do
    -#       .collection-item-text
    -#         %span.collection-item-label View all



  -# Public User Collections
  %section.container
    .gallery-header
      %span.gallery-title User Collections
      %span.bar-dets
        = @user_collections.count.to_s + " collections"
  .gallery.container.clearfix
    -@user_collections.each do |collection|
      %article#t.gallery-item.gallery-full-item.collection-item{:id => collection.id}
        .gallery-img
          =image_tag(collection.front_image.file.url(:medium)) if collection.front_image
          =link_to(collection_path(collection), class: "collection-overlay") do
            .collection-item-text
              %span.collection-item-label View collection
              =simple_format(collection.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", "")+" →", {}, wrapper_tag: "h1")

app/views/collections/new.html.haml
-# -if params[:sub] == "true"
-#   =render partial: 'subcollection_form', locals: {parent: @parent}
-# -else
-#   = render 'form'

=render partial: 'form', locals: {sub: params[:sub], parent: @parent, type: "Create new"}

app/views/collections/show.html.haml
%section.gallery-view.area
  .container
    %span.gallery-title
      =link_to "Collections", collections_path
      %span.collection__arrow
      -if params[:action] == "show_user_collection"
        =link_to user_collections_path(@user.url) do
          =current_user == @user ? "Your " : @user.name.capitalize+"'s "
          collections
        %span.collection__arrow
      -@ancestors.each_with_index do |ancestor,i|
        -if i != @ancestors.count-1
          -if params[:action] == "show_user_collection"
            =link_to ancestor.title, user_collection_path(@user.url, ancestor.url)
          -else
            =link_to ancestor.title, collection_path(ancestor.url)
        -else
          =ancestor.title
        -if i != @ancestors.count-1
          %span.collection__arrow
    .gallery-header.collection-header
      -if logged_in?
        -if current_user.admin? or @user.id == @collection.user_id
          =link_to 'Add new subcollection', new_collection_path({sub: true, parent_id:@collection.id}), class: "sub-nav-act isFirst"
          -if @collection != @archive_collection
            =link_to 'Edit collection', edit_collection_path(@collection), class: "sub-nav-act"
            =link_to 'Delete collection', @collection, method: :delete, data: { confirm: 'Are you sure?' }, class: "sub-nav-act"
      %span.bar-dets{:class => ("isFirst" unless (logged_in? && current_user.admin?) or (logged_in? and @user.id == @collection.user_id))}
        has
        =@assets.count
        -if @assets.count == 1
          image
        -else
          images
        &
        =@children.count
        -if @children.count == 1
          child collection
        -else
          child collections

  -# Sub Collections
  -if @children.count >= 1
    .container
      .gallery-header.collection-subheader
        %span.collection-subheader__heading
          Sub Collections
        %span.bar-dets
          View as
          =link_to "list", (params[:action] == "show_user_collection" ? user_collection_list_path(@user.url, @collection.url) : collection_list_path(@collection.url)) + "?view=list"
          |
          =link_to "gallery", (params[:action] == "show_user_collection" ? user_collection_list_path(@user.url, @collection.url) : collection_list_path(@collection.url)) + "?view=gallery"
    -if params[:view] == "list"
      =render :partial => "show_collections_list_view.html", locals: {children: @children, user: @user}
    -else
      =render :partial => "show_collections_gallery_view.html", locals: {children: @children, user: @user}
    .container
      = paginate @children
  -# Images
  -if @assets.count >= 1
    =render :partial => "show_assets_gallery_view.html", locals: {assets: @assets}

app/views/collections/user_collections.html.haml
%section.gallery-view.area
  .container
    %span.gallery-title
      =link_to "Collections", collections_path
      %span.collection__arrow
      =current_user == @user ? "Your " : @user.name.capitalize+"'s "
      collections
    .gallery-header.collection-header
      =link_to 'Add new collection', new_collection_path(), class: "sub-nav-act isFirst"
      %span.bar-dets
        =current_user == @user ? "You have" : @user.name.capitalize+" has"
        =@children.count
        -if @children.count == 1
          collection
        -else
          collections

  -# Sub Collections
  -if @children.count >= 1
    .container
      .gallery-header.collection-subheader
        %span.collection-subheader__heading
          Collections
        %span.bar-dets
          View as
          =link_to "list", user_collections_path(@user.url) + "?view=list"
          |
          =link_to "gallery", user_collections_path(@user.url) + "?view=gallery"
    -if params[:view] == "list"
      =render :partial => "show_collections_list_view.html", locals: {children: @children}
    -else
      =render :partial => "show_collections_gallery_view.html", locals: {children: @children}
    .container
      = paginate @children