config/routes.rb
DemarcoArchive::Application.routes.draw do

  get 'collection_items/create'
  get 'collection_items/delete'

  delete '/taggings' => 'taggings#destroy'
  post '/taggings' => 'taggings#create'
  get '/taggings' => 'taggings#show'

  get 'password_resets/new'
  get 'password_resets/edit'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/assets/new' => 'assets#new', as: :new_asset
  get '/assets/:url' => 'assets#show', as: :asset
  get '/assets' => 'assets#index', as: :assets
  patch '/assets/:url' => 'assets#update'
  get '/assets/:url/edit' => 'assets#edit', as: :edit_asset
  post '/assets/' => 'assets#create'
  get '/assets/:url/lightbox' => 'assets#lightbox', as: :asset_lightbox
  delete '/assets/:url' => 'assets#delete', as: :delete_asset

  get '/people' => 'people#index'
  get '/people/new' => 'people#new', as: :new_person
  get '/people/:url' => 'people#show', as: :person
  patch '/people/:url' => 'people#update'
  get '/people/:url/edit' => 'people#edit', as: :edit_person
  post '/people' => 'people#create'
  delete '/people/:url' => 'people#destroy', as: :delete_person

  delete 'asset_people' => 'asset_people#destroy'
  post 'asset_people' => 'asset_people#create'

  get '/collections/new' => 'collections#new', as: :new_collection
  get '/collections/:url' => 'collections#show'
  get '/collections/:url/list' => 'collections#show', as: :collection_list
  get '/collections' => 'collections#index'
  patch '/collections/:url' => 'collections#update'
  get '/collections/:url/edit' => 'collections#edit', as: :edit_collection
  get '/collections/public_collections' => 'collections#public_collections', as: :public_collections
  delete '/collections/:url' => 'collections#destroy'
  resources :collections

  post '/collection_items/' => 'collection_items#create'
  delete '/collection_items/' => 'collection_items#delete'

  get 'tags/new' => 'tags#new', as: :new_tag
  get '/tags/:url' => 'tags#show'
  get '/tags' => 'tags#index'
  patch '/tags/:url' => 'tags#update'
  get '/tags/:url/edit' => 'tags#edit', as: :edit_tag
  post '/tags' => 'tags#create'

  get '/search' => 'search#search', as: :search
  post '/search' => 'search#search'

  get '/static_text/edit' => 'static_text#edit'
  patch '/static_text' => 'static_text#update'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get '/users/:url/history' => 'users#history', as: :history
  get '/users/:url/favourites' => 'users#favorites', as: :favorites
  get '/users/:url/dashboard' => 'users#dashboard', as: :dashboard
  post '/users/:url/toggle_admin' => 'users#toggle_admin'

  resources :favorites, only: [:create, :destroy]

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "home#errors", :code => code
  end

  get '/about' => 'home#about'

  post '/home/send_contact' => 'home#send_contact'

  root 'home#index'

end

app/models/person.rb
class Person < ActiveRecord::Base

  ## Relationships
  has_many :asset_people, :dependent => :destroy
  has_many :assets, through: :asset_people
  
  belongs_to :front_image, :class_name => 'Asset'
  
  ## Validations
  validates :name, :presence => true, :uniqueness => true
  
  ### Instance methods
  has_url :url, :generated_from => :name
  
  ### Sunspot search
  
  searchable do
    text :name
    string :nationality
    string :role
    string :table_name do Person.table_name end
    
  end
  
end

# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  nationality    :string(255)
#  dob            :datetime
#  role           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  bio            :text
#  front_image_id :integer
#

app/controllers/people_controller.rb
# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  nationality    :string(255)
#  dob            :datetime
#  role           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  bio            :text
#  front_image_id :integer
#

class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    # @people = Person.all
    # @person = Person.new
    redirect_to "/search?search_type=people"
  end

  # GET /people/1
  # GET /people/1.json
  def show
    url_rewrite(Person, params, flash)
    if logged_in? && current_user.admin?
      @assets = @person.assets.page(params[:page]).order(params[:order])
    else
      @assets = @person.assets.published.page(params[:page]).order(params[:order])
    end
  end

  # GET /people/new
  def new
    if current_user && current_user.admin?
      @person = Person.new
    else
      flash[:notice] = "You do not have access to this page"
      redirect_to "/"
    end
  end

  # GET /people/1/edit
  def edit
    if current_user && current_user.admin?
      url_rewrite(Person, params, flash)
    else
      flash[:notice] = "You do not have access to this page"
      redirect_to "/"
    end
     
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person, json: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: {person: @person, errors: @person.errors }, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    puts "***** #{params} *****"
    # params[:person][:dob] = params["dob"]
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    puts "here"
    @person = Person.find(params[:url])
    @person.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: "Person was successfully deleted" }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:url].split("-").first)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :nationality, :dob, :role, :front_image_id, asset_people_attributes:[:id, :asset_id, :person_id, :_destroy])
    end
end

app/helpers/people_helper.rb
# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  nationality    :string(255)
#  dob            :datetime
#  role           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  bio            :text
#  front_image_id :integer
#

module PeopleHelper
end

app/views/people/_form.html.haml
=form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    
    =f.label :name
    %br
    =f.text_field :name
    
  .field  
    =f.label :nationality
    %br
    =f.text_field :nationality
    
  .field
    =f.label :dob
    %br
    =f.date_select :dob
    
  .field
    =f.label :role
    %br
    =f.text_field :role
    
          

  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%section.single-asset-view.area.new-asset
  %section#single-asset.container.clearfix
  
    =form_for @person do |f|
      - if @person.errors.any?
        #error_explanation
          %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
          %ul
            - @person.errors.full_messages.each do |msg|
              %li= msg
        
            
      .single-details.single-block  
        .single-extra 
          .field
  
            =f.label :name
            %br
            =f.text_field :name
            
          .field  
            =f.label :nationality
            %br
            =f.text_field :nationality
            
          .field
            =f.label :dob
            =f.date_field :dob, :class => "datepicker"
            
          .field
            =f.label :role
            %br
            =f.text_field :role
          .field
            =f.label :front_image_id
            %br
            =f.text_field :front_image_id
                      
          .actions
            =f.submit class: "btn"

app/views/people/index.html.haml
%section.gallery-view.area
  %header.container

    %section.dash-search-area.bumper
      .dash-add
        =link_to "Add new person", new_person_path, class: "btn btn-big"
      %span.form-sep
        Or  
      = render 'search/form'
  -@people.each do |person|
    %section.container.clearfix.gallery-list
      .gallery-header
        %span.gallery-title=person.name
        =link_to 'View person', "/people/#{person.url}", class: "sub-nav-act"
        =link_to 'Edit person', edit_person_path(person), class: "sub-nav-act"
        =link_to 'Delete person', person, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "sub-nav-act"
        
      
      .gallery
        -person.assets[0..2].each do |asset|
          
          %article#t.gallery-item.gallery-full-item.flex-wrap.flex-center{:id => asset.id}
            .gallery-img.flex-stretch.flex-wrap.flex-center
              =image_tag(asset.file.url(:medium))
            
           
            =link_to(asset_path(asset), class: "gallery-overlay") do
    	        
            
              =simple_format(asset.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", ""), {}, wrapper_tag: "h1")
        -if person.assets.count > 3      
          %article#t.gallery-item.gallery-full-item.flex-wrap.flex-center
            =link_to("/people/#{person.url}", class: "gallery-more") do
              View more &#8594

              


=link_to "New Person", new_person_path, class: "btn btn-big"

app/views/people/new.html.haml
%section.single-asset-view.area.new-asset
  %section#single-asset.container.clearfix
  
    =form_for @person do |f|
      - if @person.errors.any?
        #error_explanation
          %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
          %ul
            - @person.errors.full_messages.each do |msg|
              %li= msg
        
            
      .single-details.single-block  
        .single-extra 
          .field
  
            =f.label :name
            %br
            =f.text_field :name
            
          .field  
            =f.label :nationality
            %br
            =f.text_field :nationality
            
          .field
            =f.label :dob
            %br
            =f.date_select :dob
            
          .field
            =f.label :role
            %br
            =f.text_field :role
          .field
            =f.label :front_image_id
            %br
            =f.text_field :front_image_id
        
                      
          .actions
            =f.submit class: "btn"

app/views/people/show.html.haml
%section.container.clearfix.gallery-list
%section.gallery-view.area
  %section.container
    .gallery-header
      %span.gallery-title=@person.name
      %span.bar-dets
        Role:
        =@person.role
      %span.bar-dets
        Appears in
        =@assets.count
        -if @assets.count == 1
          image
        -else
          images
      -if current_user && current_user.admin?
        %span.bar-dets
          =link_to "Edit Person", edit_person_path
        %span.bar-dets
          =link_to "Delete Person", delete_person_path, method: :delete


  %section.gallery.container.clearfix
    -if @assets
      -@assets.each do |asset|
        %article#t.gallery-item.gallery-full-item.flex-wrap.flex-center{:id => asset.id}
          .gallery-img.flex-stretch
            =image_tag(asset.file.url(:medium))
          =link_to(asset_lightbox_path(asset.url), class: "gallery-overlay gallery-popup") do
            =simple_format(asset.title.gsub("<br />\r\r", "\r").gsub("<p>", "").gsub("</p>", ""), {}, wrapper_tag: "h1")
-#       .clearfix
-#       =paginate @assets