config/routes.rb
DemarcoArchive::Application.routes.draw do

  get 'collection_items/create'
  get 'collection_items/delete'

  delete '/taggings' => 'taggings#destroy'
  post '/taggings' => 'taggings#create'
  get '/taggings' => 'taggings#show'

  get 'password_resets/new'
  get 'password_resets/edit'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/assets/new' => 'assets#new', as: :new_asset
  get '/assets/:url' => 'assets#show', as: :asset
  get '/assets' => 'assets#index', as: :assets
  patch '/assets/:url' => 'assets#update'
  get '/assets/:url/edit' => 'assets#edit', as: :edit_asset
  post '/assets/' => 'assets#create'
  get '/assets/:url/lightbox' => 'assets#lightbox', as: :asset_lightbox
  delete '/assets/:url' => 'assets#delete', as: :delete_asset

  get '/people' => 'people#index'
  get '/people/new' => 'people#new', as: :new_person
  get '/people/:url' => 'people#show', as: :person
  patch '/people/:url' => 'people#update'
  get '/people/:url/edit' => 'people#edit', as: :edit_person
  post '/people' => 'people#create'
  delete '/people/:url' => 'people#destroy', as: :delete_person

  delete 'asset_people' => 'asset_people#destroy'
  post 'asset_people' => 'asset_people#create'

  get '/collections/new' => 'collections#new', as: :new_collection
  get '/collections/:url' => 'collections#show'
  get '/collections/:url/list' => 'collections#show', as: :collection_list
  get '/collections' => 'collections#index'
  patch '/collections/:url' => 'collections#update'
  get '/collections/:url/edit' => 'collections#edit', as: :edit_collection
  get '/collections/public_collections' => 'collections#public_collections', as: :public_collections
  delete '/collections/:url' => 'collections#destroy'
  resources :collections

  post '/collection_items/' => 'collection_items#create'
  delete '/collection_items/' => 'collection_items#delete'

  get 'tags/new' => 'tags#new', as: :new_tag
  get '/tags/:url' => 'tags#show'
  get '/tags' => 'tags#index'
  patch '/tags/:url' => 'tags#update'
  get '/tags/:url/edit' => 'tags#edit', as: :edit_tag
  post '/tags' => 'tags#create'

  get '/search' => 'search#search', as: :search
  post '/search' => 'search#search'

  get '/static_text/edit' => 'static_text#edit'
  patch '/static_text' => 'static_text#update'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get '/users/:url/history' => 'users#history', as: :history
  get '/users/:url/favourites' => 'users#favorites', as: :favorites
  get '/users/:url/dashboard' => 'users#dashboard', as: :dashboard
  post '/users/:url/toggle_admin' => 'users#toggle_admin'

  resources :favorites, only: [:create, :destroy]

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "home#errors", :code => code
  end

  get '/about' => 'home#about'

  post '/home/send_contact' => 'home#send_contact'

  root 'home#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search

    ## Instance variables
    @people = Person.all.order(name: :asc)

    @tags = Tag.all.map{|t| t.name}.sort
    @nationalities = Person.all.select{|p| p.nationality != nil}.map{|p| p.nationality}.uniq!.sort


    if current_user
      if current_user.admin?
        @mediums = Asset.all.select{|a| a.medium != nil}.map{|a| a.medium}.uniq!.sort
        @catalogue_numbers = Asset.all.select{|a| a.archive_reference != nil}.map{|a| a.archive_reference}.uniq!.compact.sort
      else
        @mediums = Asset.published.select{|a| a.medium != nil}.map{|a| a.medium}.uniq!.sort
        @catalogue_numbers = Asset.published.select{|a| a.archive_reference != nil}.map{|a| a.archive_reference}.uniq!.compact.sort
      end
    else
      @mediums = Asset.published.select{|a| a.medium != nil}.map{|a| a.medium}.uniq!.sort
      @catalogue_numbers = Asset.published.select{|a| a.archive_reference != nil}.map{|a| a.archive_reference}.uniq!.compact.sort
    end

    if params[:search_type] == "assets"
      
      ### Asset search
      @search = Sunspot.search Asset do |query|
        
        if current_user
          if current_user.admin?
            if params[:status] && params[:status] == "unpublished"
              query.with(:status, "Unpublished")
            else
              query.with(:status).any_of(["Published", "Unpublished"])
            end
          else
            query.with(:status, "Published")
          end
        else
          query.with(:status, "Published")
        end

        # General Keyword query
        if params[:q]
          query.fulltext params[:q] do
            minimum_match 2
          end
        end


        ## Date queries
        if params[:after] && params[:after] != ""
          date = Date.parse(params[:after])
          query.with(:date_from).greater_than(date)
        end

        if params[:before] && params[:before] != ""
          date = Date.parse(params[:before])
          query.with(:date_from).less_than(date)
        end

        if params[:between]
          start_date = Date.parse(params[:between].split("-")[0])
          end_date = Date.parse(params[:between].split("-")[1])
          query.with(:date_from).between(start_date..end_date)
        end

        if params[:on]
          date = Date.parse(params[:on])
          query.with(:date_from).between(date..date)
        end


        ## Person
        if params[:people]
          people = params[:people]
          if params[:people_combo]=="all"
            query.with(:people).all_of(people)
          else
            query.with(:people).any_of(people)
          end

        end

        if params[:nationality]
          nationality = params[:nationality]
          if params[:nationality_combo]=="all"
            query.with(:people_nationality).all_of(nationality)
          else
            query.with(:people_nationality).any_of(nationality)
          end
        end

     ## Metadata Queries TODO - fix these so that they handle single entries

        # Medium - uses an example of passing in an optional all, with comma seperated values
        if params[:medium]
          # medium_array = params[:medium]
          query.with(:medium, params[:medium])
        end

        ## Archive codes
        if params[:archive_original_code]
          query.with(:archive_original_code, params[:archive_original_code])
        end

        if params[:archive_reference]
          query.with(:archive_reference, params[:archive_reference])
        end

        if params[:tags]
          tags_array = params[:tags]
          if params[:tags_combo] == "all"
            query.with(:tags).all_of(tags_array)
          else
            query.with(:tags).any_of(tags_array)
          end
        end


        if params[:colour]
          if params[:colour] == "true"
            query.with(:colour, true)
          elsif params[:colour] == "false"
            query.with(:colour).any_of([true, false])
          end
        end

        ## Untitled
        # if params[:title]
        #   query.with(:title, params[:title])
        # end
        query.paginate :page => params[:page], :per_page => 20
      end

    ## Search for collections
    elsif params[:search_type] == 'collections'


      @search = Sunspot.search Collection do |query|

        ### Defaults to showing public collections only
        ### Only the 'mine' param will show private collections, and only those belonging to the signed in user.

        ## Logged in validation for mine only scoping, with private collections
        if params[:mine] == 'true' && logged_in?

            query.with(:public).any_of([true, false])
            query.with(:user_id).equal_to(current_user.id)

            if params[:asset_count]
              query.with(:collection_items_count).greater_than(params[:asset_count].to_i-1)
            end

        else

          ## Default param scoping available to everybody
          ## Default search
          query.with(:public, true)
          query.keywords params[:q]

          ## Items count

          if params[:asset_count]
            query.with(:collection_items_count).greater_than(params[:asset_count].to_i-1)
          end

          ## Just public user collections
          if params[:user_collections]

            if params[:user_collections] == 'true'
              query.with(:user_id).greater_than(1)
            end

            if params[:mine]
              query.with(:public).any_of([true, false])
            else
              query.with(:public, true)
            end
          end

        end
        query.paginate :page => params[:page], :per_page => 22
      end


    ## Search for people
    elsif params[:search_type] == 'people'

      @search = Sunspot.search Person do |query|
        query.keywords params[:q]

        if params[:nationality]
          query.with(:nationality, params[:nationality])
        end

        if params[:name]
          query.with(:name).any_of(params[:name])
        end

      end

    ## Search everything
    else
      ### General search
      @search = Sunspot.search Asset, Collection, Person do |query|

        if !current_user || (current_user && !current_user.admin?)
          query.without(:status, "Unpublished")
        end

        query.fulltext params[:q]


        query.without(:public, false)



        if params[:name]
          query.with(:name).equal_to(params[:name])
        end

        query.paginate :page => params[:page], :per_page => 20
      end

    end


    respond_to do |format|
      format.html { render "search"}
      format.js {}
    end
  end


end

app/views/search/_filter_panel.html.haml
.container.filter-panel#fpanel
  .gallery-header
    %span.gallery-title Advanced asset filtering

  .filter-panel-form.clearfix#fpform
    =form_tag("/search", method: "get", remote: true, id: "filterForm") do |form|
      =hidden_field_tag "search_type", "assets"
      =hidden_field_tag "q", params[:q], id: "filter-query"

      -#%h2 People
      .field-wrap

        .field#peopleform
          .filter-item
            =select_tag('people[]',options_from_collection_for_select(@people, 'name', 'name', params[:people]), {:multiple=>"true", :id => "filter-people", :placeholder => "People"})
            .filter-toggle
              .filter-radio
                =radio_button_tag :people_combo, "any", params[:people_combo] == "any", :class => "filter-radio-any"
                =label_tag :any_any, "Any people", :class => "radio-label"
                %br
                =radio_button_tag :people_combo, "all", params[:people_combo] == "all", :class => "filter-radio-all"
                =label_tag :all_all, "All people", :class => "radio-label"
              .toggle-wrap
                .toggle-button{:class => ("toggleOn" if params[:people_combo] == "all")}
                  .toggle-knob-holder
                    .toggle-knob
                %span.toggle-info
                  Only show results matching
                  %span.toggle-em all
                  people


          .filter-item
            =select_tag('nationality[]', options_for_select(@nationalities, params[:nationality]), {:multiple=>"true", :id => "filter-nationality", :placeholder => "Nationality"})
            .filter-toggle
              .filter-radio
                =radio_button_tag :nationality_combo, "any", params[:nationality_combo] == "any", :class => "filter-radio-any"
                =label_tag :any_any, "Any nationality", :class => "radio-label"
                %br
                =radio_button_tag :nationality_combo, "all", params[:nationality_combo] == "all", :class => "filter-radio-all"
                =label_tag :all_all, "All nationality", :class => "radio-label"
              .toggle-wrap
                .toggle-button{:class => ("toggleOn" if params[:nationality_combo] == "all")}
                  .toggle-knob-holder
                    .toggle-knob
                %span.toggle-info
                  Only show results matching
                  %span.toggle-em all
                  nationalities




          -#/ For testing
          -#params[:people]
          -#params[:nationality]
          -#=params



        .field#mediumform
          .filter-item
            =select_tag('medium[]', options_for_select(@mediums, params[:medium]), {:multiple=>"true", :id => "filter-mediums", :placeholder => "Medium"})


        -#.field#dateform
          -#.filter-item
            -#=label_tag "Date From"
            -#=date_field_tag :after, Date.new(1950,1,1), :placeholder => "Date After"
            -#=label_tag "Date To"
            -#=date_field_tag :before, Date.today, :placeholder => "Date Before"



        .field#tagform
          .filter-item
            =select_tag('tags[]', options_for_select(@tags, params[:tags]), {:multiple=>"true", :id => "filter-tags", :placeholder => "Tags"})
            .filter-toggle
              .filter-radio
                =radio_button_tag :tags_combo, "any", params[:tags_combo] == "any", :class => "filter-radio-any"
                =label_tag :any_any, "Any tags", :class => "radio-label"
                %br
                =radio_button_tag :tags_combo, "all", params[:tags_combo] == "all", :class => "filter-radio-all"
                =label_tag :all_all, "All tags", :class => "radio-label"
              .toggle-wrap
                .toggle-button{:class => ("toggleOn" if params[:tags_combo] == "all")}
                  .toggle-knob-holder
                    .toggle-knob
                %span.toggle-info
                  Only show results matching
                  %span.toggle-em all
                  tags


        .field#dateform
          .filter-item.date-picker-item
            =label_tag "Date From"
            =date_field_tag :after, nil, :placeholder => "Date After", :class => "datepicker"
          .filter-item.date-picker-item
            =label_tag "Date To"
            =date_field_tag :before, nil, :placeholder => "Date Before", :class => "datepicker"

        .field#referenceform
          .filter-item
            %br
            =select_tag('archive_reference', options_for_select(@catalogue_numbers, params[:archive_reference]), {:multiple=>"false", :id => "filter-catalogue_numbers", :placeholder => "Catalogue number"})

        .field#colour
          %span.field-label.hide Colour
          =params[:colour]
          .filter-toggle
            .filter-radio
              =radio_button_tag :colour, "false", params[:colour] == "false", :class => "filter-radio-any"
              =label_tag :colour_true, "B&W", :class => "radio-label"
              %br
              =radio_button_tag :colour, "true", params[:colour] == "true", :class => "filter-radio-all"
              =label_tag :colour_false, "Colour", :class => "radio-label"
            .toggle-wrap
              .toggle-button{:class => ("toggleOn" if params[:colour] == "true")}
                .toggle-knob-holder
                  .toggle-knob
              %span.toggle-info
                Only show
                %span.toggle-em colour
                items

        -if current_user && current_user.admin?
          .field#status
            %span.field-label.hide Status
            .filter-toggle
              .filter-radio
                =radio_button_tag :status, "all", params[:status] == "all", :class => "filter-radio-any"
                =label_tag :status_all, "All", :class => "radio-label"
                %br
                =radio_button_tag :status, "unpublished", params[:status] == "unpublished", :class => "filter-radio-all"
                =label_tag :status_unpublished, "Unpublished", :class => "radio-label"
              .toggle-wrap
                .toggle-button{:class => ("toggleOn" if params[:status] == "unpublished")}
                  .toggle-knob-holder
                    .toggle-knob
                %span.toggle-info
                  Only show
                  %span.toggle-em unpublished
                  items






      =submit_tag "", class: "search-btn"

app/views/search/_form.html.haml
.dash-search
  = form_tag("/search", method: "get", remote: true, id: "keyword-form") do
    .flex-wrap
      = label_tag(:q, "Search for:", class: "label-hide")
      = search_field_tag :q , params[:q], placeholder: "Enter search terms", class: "input-search flex-stretch", id: 'keyword-query'



      = submit_tag "", class: "search-btn"
    .field#search-type
      .search-type-radio
        =radio_button_tag :search_type, "all", params[:search_type] != "assets" && params[:search_type] != "people" && params[:search_type] != "collections", :class => "filter-radio-all"
        =label_tag :search_all, "All", :class => "radio-label"
      .search-type-radio
        =radio_button_tag :search_type, "assets", params[:search_type] == "assets", :class => "filter-radio-any"
        =label_tag :search_assets, "Assets Only", :class => "radio-label"
      .search-type-radio
        =radio_button_tag :search_type, "people", params[:search_type] == "people", :class => "filter-radio-all"
        =label_tag :search_people, "People Only", :class => "radio-label"
      .search-type-radio
        =radio_button_tag :search_type, "collections", params[:search_type] == "collections", :class => "filter-radio-all"
        =label_tag :search_collections, "Collections Only", :class => "radio-label"

app/views/search/_form_top.html.haml
.top-search
  = form_tag("/search", method: "get") do
    .flex-wrap.flex-center
      = label_tag(:q, "Search for:", class: "label-hide")
      .flex-wrap.flex-stretch.search-top-wrap
        = search_field_tag :q ,nil, placeholder: "Search for an asset", class: "input-search input-search-sm flex-stretch", autocomplete: "off", id: 'nav-query'


        = submit_tag "", class: "search-btn-sm"
      =link_to(search_path, class: "btn-text-top") do
        Advanced search &#8594

app/views/search/_results.html.haml
%section.gallery-view
  .gallery-header.container
    %span.gallery-title #{search.total} results

  %section.gallery.container.clearfix

    -search.each_hit_with_result do |hit, result|

      -if hit.class_name == "Asset"
        =render :partial => 'search/result_types/asset', locals: {hit: hit, asset: result}
      -if hit.class_name == "Collection"
        =render :partial => 'search/result_types/collection', locals: {hit: hit, collection: result}
      -if hit.class_name == "Person"
        =render :partial => 'search/result_types/person', locals: {hit: hit, person: result}


  =paginate search.results

app/views/search/search.html.haml
.pad-top
  -if @search

    -if params[:all_people]
      = params[:all_people].split(",")

    .container.flex-wrap
      = render 'form'

    = render 'filter_panel'
    .area
      = render :partial => "results", locals: {search: @search}


  -else
    %h2 No results

app/views/search/search.js.erb
$(".gallery-view").infinitescroll('destroy');
$(".gallery-view").html("<%= escape_javascript( render('results', {search: @search})) %>");
galleryInit();

$(".gallery-view").infinitescroll({
    navSelector: "nav.pagination",
    nextSelector: "nav.pagination a[rel=next]",
    itemSelector: ".gallery"
    },

    function(arrayOfNewElems){
      galleryInit();

    }

    );